modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/itsmeow/FluidGun/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sbm-fluid-gun"
logoFile="fluid_gun_mod_icon.png"
credits="its_meow: for programming, art, idea"
authors="its_meow"
license="CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode"
[[mods]]
    modId="fluidgun"
    version="${file.jarVersion}"
    displayName="[SBM] Fluid Gun"
    description='''
    A mod adding a fluid gun which allows players to manipulate liquids at a range.'''
[[dependencies.fluidgun]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.21,)"
    ordering="NONE"
    side="BOTH"